name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag m0o3atef/docker-react
    
    - name: Test the Docker image
      run: docker run -e CI=true m0o3atef/docker-react npm run test
    
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
    
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: udemy-frontend
        environment_name: udemy-frontend-env
        version_label: ${{ github.sha }}
        region: eu-north-1
        deployment_package: deploy.zip
        existing_bucket_name: elasticbeanstalk-eu-north-1-877533349104