name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag m0o3atef/docker-react
    - name: Test the Docker image
      run: docker run -e CI=true m0o3atef/docker-react npm run test
